=== https-gitlab-com-OKEAMAH002/literate-carnival/perf/go/config/validate/instanceConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/perf/go/config/instance-config",
  "$ref": "#/$defs/InstanceConfig",
  "$defs": {
    "AnomalyConfig": {
      "properties": {
        "settling_time": {
          "$ref": "#/$defs/DurationAsString"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "AuthConfig": {
      "properties": {
        "header_name": {
          "type": "string"
        },
        "email_regex": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "header_name"
      ]
    },
    "CacheConfig": {
      "properties": {
        "memcached_servers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "namespace": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "memcached_servers",
        "namespace"
      ]
    },
    "CulpritNotifyConfig": {
      "properties": {
        "notifications": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "culprit_subject": {
          "type": "string"
        },
        "culprit_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notifications"
      ]
    },
    "DataStoreConfig": {
      "properties": {
        "datastore_type": {
          "type": "string"
        },
        "connection_string": {
          "type": "string"
        },
        "tile_size": {
          "type": "integer"
        },
        "cache": {
          "$ref": "#/$defs/CacheConfig"
        },
        "enable_follower_reads": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "datastore_type",
        "connection_string",
        "tile_size"
      ]
    },
    "DurationAsString": {
      "type": "string",
      "title": "Duration",
      "description": "A golang time.Duration serialized as a string."
    },
    "Favorites": {
      "properties": {
        "sections": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "sections"
      ]
    },
    "FavoritesSectionConfig": {
      "properties": {
        "name": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "links"
      ]
    },
    "FavoritesSectionLinkConfig": {
      "properties": {
        "text": {
          "type": "string"
        },
        "href": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "text",
        "href",
        "description"
      ]
    },
    "GitRepoConfig": {
      "properties": {
        "git_auth_type": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "start_commit": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        },
        "file_change_marker": {
          "type": "string"
        },
        "debounce_commit_url": {
          "type": "boolean"
        },
        "commit_url": {
          "type": "string"
        },
        "commit_number_regex": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider",
        "url",
        "dir"
      ]
    },
    "IngestionConfig": {
      "properties": {
        "source_config": {
          "$ref": "#/$defs/SourceConfig"
        },
        "branches": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "file_ingestion_pubsub_topic_name": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_config",
        "branches",
        "file_ingestion_pubsub_topic_name"
      ]
    },
    "InstanceConfig": {
      "properties": {
        "URL": {
          "type": "string"
        },
        "backend_host_url": {
          "type": "string"
        },
        "allowed_hosts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "contact": {
          "type": "string"
        },
        "invalid_param_char_regex": {
          "type": "string"
        },
        "fetch_chrome_perf_anomalies": {
          "type": "boolean"
        },
        "feedback_url": {
          "type": "string"
        },
        "chat_url": {
          "type": "string"
        },
        "help_url_override": {
          "type": "string"
        },
        "bug_host_url": {
          "type": "string"
        },
        "favorites": {
          "$ref": "#/$defs/Favorites"
        },
        "filter_parent_traces": {
          "type": "boolean"
        },
        "trace_sample_proportion": {
          "type": "number"
        },
        "trace_format": {
          "type": "string"
        },
        "need_alert_action": {
          "type": "boolean"
        },
        "use_regression2_schema": {
          "type": "boolean"
        },
        "auth_config": {
          "$ref": "#/$defs/AuthConfig"
        },
        "data_store_config": {
          "$ref": "#/$defs/DataStoreConfig"
        },
        "ingestion_config": {
          "$ref": "#/$defs/IngestionConfig"
        },
        "git_repo_config": {
          "$ref": "#/$defs/GitRepoConfig"
        },
        "notify_config": {
          "$ref": "#/$defs/NotifyConfig"
        },
        "culprit_notify_config": {
          "$ref": "#/$defs/CulpritNotifyConfig"
        },
        "anomaly_config": {
          "$ref": "#/$defs/AnomalyConfig"
        },
        "query_config": {
          "$ref": "#/$defs/QueryConfig"
        },
        "ga_measurement_id": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "URL",
        "contact",
        "data_store_config",
        "ingestion_config",
        "git_repo_config",
        "notify_config"
      ]
    },
    "NotifyConfig": {
      "properties": {
        "notifications": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "missing_subject": {
          "type": "string"
        },
        "missing_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notifications"
      ]
    },
    "QueryConfig": {
      "properties": {
        "include_params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "default_param_selections": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "default_url_values": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "redis_config": {
          "$ref": "#/$defs/RedisConfig"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "RedisConfig": {
      "properties": {
        "project": {
          "type": "string"
        },
        "zone": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SourceConfig": {
      "properties": {
        "source_type": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "subscription": {
          "type": "string"
        },
        "dl_topic": {
          "type": "string"
        },
        "dl_subscription": {
          "type": "string"
        },
        "sources": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reject_if_name_matches": {
          "type": "string"
        },
        "accept_if_name_matches": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_type",
        "project",
        "topic",
        "subscription",
        "sources"
      ]
    }
  }
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/perf/configs/android2.json
{
    "URL": "https://androidx2-perf.skia.org",
    "contact": "http://go/androidx-discuss",
    "feedback_url": "https://issuetracker.google.com/issues/new?component=1547614&template=1970127",
    "trace_sample_proportion": 0.2,
    "notify_config": {
        "notifications": "markdown_issuetracker",
        "issue_tracker_api_key_secret_project": "skia-infra-public",
        "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey",
        "subject": "{{ .Alert.DisplayName }} - Regression found between {{ buildIDFromSubject .PreviousCommit.Subject }} and {{ buildIDFromSubject .Commit.Subject }}",
        "body": [
            "Perf Regression ({{ .Cluster.StepFit.Status }}) found, matching {{ .Cluster.Num }} tracked metrics from benchmarks.",
            "",
            "To triage this regression, see the guide at [go/androidx-bench-triage](http://go/androidx-bench-triage).",
            "",
            "* [Graph on dashboard]({{ .ViewOnDashboard }})",
            "* [Alert details]({{ .URL }}/g/t/{{ .Commit.GitHash }})",
            "* [CLs in build range ({{ buildIDFromSubject .PreviousCommit.Subject }} through {{ buildIDFromSubject .Commit.Subject }}\\]](https://android-build.corp.google.com/{{ buildIDFromSubject .Commit.Subject }}/branches/aosp-androidx-main/targets/androidx/cls?end={{ buildIDFromSubject .PreviousCommit.Subject }})",
            "* [{{ .Alert.DisplayName }} alert config]({{ .URL }}/a/?{{ .Alert.IDAsString }})",
            "",
            "Tests affected:",
            "```",
            "{{ range index .ParamSet \"test\" }} {{ . }}",
            "{{end}}```",
            "",
            "Devices affected:",
            "```",
            "{{ range index .ParamSet \"device_name\" }} {{ . }}",
            "{{end}}```",
            "API Level:",
            "```",
            "{{ range index .ParamSet \"sdk_release_name\" }} {{ . }}",
            "{{end}}```",
            ""
        ]
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/androidx?sslmode=disable",
        "tile_size": 8192
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-android2-production",
            "subscription": "perf-ingestion-android2-production-prod",
            "sources": [
                "gs://android-perf-2/android2"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "provider": "gitiles",
        "url": "https://android.googlesource.com/platform/superproject",
        "dir": "/tmp/androidx",
        "debounce_commit_url": false,
        "branch": "androidx-main",
        "start_commit": "5f8b9aa0feafff7548336998a17723cb792cdb53"
    },
    "anomaly_config": {
        "settling_time": "5h"
    }
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/perf/configs/cdb-ct-prod.json
{
  "URL": "https://ct-perf.skia.org",
  "contact": "https://bugs.skia.org",
  "trace_sample_proportion": 0.01,
  "use_regression2_schema": true,
  "notify_config": {
    "notifications": "html_email"
  },
  "auth_config": {
    "header_name": "X-WEBAUTH-USER"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/ct?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-ct-production",
      "subscription": "perf-ingestion-ct-cdb-prod",
      "sources": [
        "gs://cluster-telemetry-perf/ingest"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "provider": "gitiles",
    "url": "https://skia.googlesource.com/perf-ct",
    "dir": "/tmp/ct",
    "debounce_commit_url": false
  }
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/perf/configs/chrome-perf-non-public.json
{
    "URL": "https://chrome-perf.corp.goog",
    "ga_measurement_id": "G-LEQSJH1GXP",
    "allowed_hosts": [],
    "backend_host_url": "perf-be-chrome-non-public.perf.svc.cluster.local:8000",
    "contact": "browser-perf-engprod@google.com",
    "trace_sample_proportion": 1.0,
    "invalid_param_char_regex": "([^a-zA-Z0-9!~@#$%^&*()+ :\\._\\-])",
    "fetch_chrome_perf_anomalies": true,
    "use_regression2_schema": true,
    "bug_host_url": "https://issues.chromium.org",
    "feedback_url": "http://go/berf-skia-feedback",
    "chat_url": "http://go/berf-skia-chat",
    "filter_parent_traces": true,
    "notify_config": {
        "notifications": "chromeperf"
    },
    "culprit_notify_config": {
        "notifications": "markdown_issuetracker",
        "issue_tracker_api_key_secret_project": "skia-infra-public",
        "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey"
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/chrome_int?sslmode=disable",
        "tile_size": 8192,
        "enable_follower_reads": true
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-chrome-non-public",
            "subscription": "perf-ingestion-chrome-non-public-prod",
            "dl_topic": "perf-ingestion-chrome-non-public-dl",
            "dl_subscription": "perf-ingestion-chrome-non-public-dl-prod",
            "sources": [
                "gs://chrome-perf-non-public/ingest"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "provider": "gitiles",
        "url": "https://chromium.googlesource.com/chromium/src",
        "dir": "/tmp/checkout",
        "debounce_commit_url": false,
        "file_change_marker": "",
        "start_commit": "b7fa4587f55a066e97f79b4c97ed785dc217064b",
        "commit_number_regex": "Cr-Commit-Position: refs/heads/(main|master)@\\{#(.*)\\}"
    },
    "query_config": {
        "include_params": [
            "benchmark",
            "bot",
            "test",
            "subtest_1",
            "subtest_2",
            "subtest_3"
        ],
        "default_param_selections": {
            "stat": ["value"]
        },
        "default_url_values": {
            "summary": "true"
        },
        "redis_config": {
            "project": "skia-infra-corp",
            "zone": "us-central1",
            "instance": "skia-query"
        }
    },
    "help_url_override": "http://go/chrome-perf-user-doc",
    "trace_format": "chrome",
    "need_alert_action": true
}
