=== https-gitlab-com-OKEAMAH002/literate-carnival/tool/go/tool/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/tool/go/tool/tool",
  "$ref": "#/$defs/Tool",
  "$defs": {
    "Tool": {
      "properties": {
        "id": {
          "type": "string"
        },
        "domain": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "phase": {
          "type": "string"
        },
        "teams_id": {
          "type": "string"
        },
        "code_path": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "audience": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "adoption_stage": {
          "type": "string"
        },
        "landing_page": {
          "type": "string"
        },
        "docs": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "feedback": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "resources": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "id",
        "domain",
        "display_name",
        "description",
        "phase",
        "teams_id",
        "code_path",
        "audience",
        "adoption_stage",
        "landing_page",
        "docs",
        "feedback",
        "resources"
      ]
    }
  }
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/tool/configs/gerrit.json
{
    "id": "gerrit",
    "domain": "Source",
    "display_name": "Gerrit",
    "description": "Gerrit is a web-based team code collaboration tool enabling software developers to review each other's code modifications using a Web browser.",
    "phase": "GA",
    "teams_id": "8953724333",
    "code_path": [],
    "audience": [
        "Chrome",
        "PEEPSI"
    ],
    "adoption_stage": "All",
    "landing_page": "https://goto.google.com/cider-g",
    "docs": {
        "Overview": "https://gerrit-review.googlesource.com/Documentation/intro-gerrit-walkthrough.html"
    },
    "feedback": {
        "Help": "https://goto.google.com/git-help"
    },
    "resources": {}
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/tool/configs/depottools.json
{
    "id": "depot_tools",
    "domain": "Source",
    "display_name": "depot_tools",
    "description": "A package of scripts to manage checkouts and code reviews. The depot_tools package includes gclient, gcl, git-cl, repo, and others.",
    "phase": "GA",
    "teams_id": "1201906511198",
    "code_path": [
        "https://chromium.googlesource.com/chromium/tools/depot_tools/+/refs/heads/main"
    ],
    "audience": [
        "Chrome",
        "PEEPSI"
    ],
    "adoption_stage": "All",
    "landing_page": "https://chromium.googlesource.com/chromium/tools/depot_tools/+/HEAD/README.md",
    "docs": {
        "git cl": "https://chromium.googlesource.com/chromium/tools/depot_tools/+/HEAD/README.git-cl.md",
        "gclient": "https://chromium.googlesource.com/chromium/tools/depot_tools/+/HEAD/README.gclient.md"
    },
    "feedback": {
        "Bugs": "https://bugs.chromium.org/p/chromium/issues/entry?components=Infra%3ESDK",
        "Forum": "https://groups.google.com/a/chromium.org/forum/#!forum/infra-dev"
    },
    "resources": {}
}

=== https-gitlab-com-OKEAMAH002/literate-carnival/tool/configs/skiaperf.json
{
    "id": "skiaperf",
    "domain": "Testing",
    "display_name": "Skia Perf",
    "description": "Perf is a web application for analyzing, exploring, and monitoring performance metrics.",
    "phase": "GA",
    "teams_id": "1346063870",
    "code_path": [
        "https://skia.googlesource.com/buildbot/+/refs/heads/main/perf/"
    ],
    "audience": [
        "Chrome"
    ],
    "adoption_stage": "Conditionally",
    "landing_page": "https://goto.google.com/skiaperf",
    "docs": {
        "User Manual": "https://goto.google.com/perf-user-doc",
        "Uploading Data": "https://skia.googlesource.com/buildbot/+/refs/heads/main/perf/FORMAT.md",
        "Command line tool": "https://skia.googlesource.com/buildbot/+/refs/heads/main/perf/PERFTOOL.md",
        "Design": "https://skia.googlesource.com/buildbot/+/refs/heads/main/perf/DESIGN.md"
    },
    "feedback": {
        "Bugs": "https://issues.skia.org/issues/new?component=1389499&template=1850647",
        "New Instance": "https://g-issues.skia.org/issues/new?component=1389499&template=1850673"
    },
    "resources": {
        "Announcements": "https://groups.google.com/a/google.com/g/skia-perf-announce"
    }
}
